### PR TITLE
one more for irc on the welcome

### PR DESCRIPTION
**Pull request by zekiel**
//cc @talsraviv

### CODE REVIEW

**Comment by jbarrett** [comment]
Could we not link to webchat? It only results in people who don't understand IRC coming on the channel and getting pissed off.

**Comment by talsraviv** [comment]
@zekiel same as this or in addition?

https://github.com/duckduckgo/duckduckhack-docs/commit/9046066ed8f7f5d3b95809fcddb57f3225d1087f

**Comment by zekiel** [comment]
@jbarrett  of course. I'll update this particular one. 

@talsraviv  the other links are at the bottoms of the pages so this one is for people who hit Welcome and are immediately in need of help.

**Comment by jbarrett** [comment]
:+1: Thanks @zekiel @talsraviv!

**Pull request merged**
