### PR TITLE
Add missing attributes

### PR DESCRIPTION
**Pull request by moollaza**
Added descriptions for `is_cached`, `proxy_cache_valid`, `alt_to`

Page in docs: https://docs.duckduckhack.com/backend-reference/spice-attributes.html

### CODE REVIEW

**Comment by moollaza** [comment]
@tagawa mind taking a look?

**Comment by tagawa** [comment]
Thanks @moollaza. I made a few fixes directly to your branch - hope that's OK.

**Comment by moollaza** [comment]
@tagawa thanks a lot! I definitely should have re-read that more carefully before committing...

**Comment by tagawa** [comment]
No problem - you're working too hard!

**Pull request merged**
