### PR TITLE
Added shell completion entry for fish shell

### PR DESCRIPTION
**Pull request by gabriellhrn**
I added an entry to the documentation to include duckpan completions in fish shell.

### CODE REVIEW

**Comment by moollaza** [comment]
@gabriellhrn thanks!

**Comment by alohaas** [comment]
@gabriellhrn , thanks again for improving our documentation! You’ve done a great job here and we'd like you to help our community tackle the next big challenge – our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 
- Create a new Instant Answer to increase our Programming IA coverage

OR
- Test live programming Instant Answers (or those in development) for bugs and suggest improvements 

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Comment by jagtalon** [comment]
fishfish_logo

**Comment by gabriellhrn** [comment]
@alohaas Thanks! I'll take a look at it and see what I can do to help :smile:

**Comment by alohaas** [comment]
@gabriellhrn please don't hesitate to reach out if you have any questions!

**Pull request merged**
