### PR TITLE
Maintainer tweak

### PR DESCRIPTION
**Pull request by zachthompson**
We don't need proof of experience or interest other than the request...yet.

### CODE REVIEW

**Comment by GuiltyDolphin** [comment]
@zachthompson Hmm... I'm with @zekiel in adding this (we've discussed); though I believe you're heading the maintainer movement?

@zekiel We'd probably want to standardize this a bit more? I.e, have a template for people to fill out rather than describing what should be included.

**Comment by zachthompson** [comment]
At this point we have no reason to believe people need to justify the request.  Making it is enough.  We are still mid-test as well and probably shouldn't be making substantive changes to the docs.  It could turn people away from requesting, e.g. what "experience" do I have with reverse text or randagrams?!

**Comment by GuiltyDolphin** [comment]
@zachthompson Hmm... Good point, I'm more concerned about the 'larger' IAs that may end up with no maintainer, rather than the 'niche' Instant Answer (such as those mentioned).

I still think something like "Why I want to be maintainer" might be good - they'd have a reason if they were asking, surely?

**Comment by zekiel** [comment]
Sorry -- I missed this PR before making a change to Master. @GuiltyDolphin  @zachthompson  I (confusingly) agree with both of you. 
1. the process should be simple 
2. simply asking for maintainership is probably enough of a signal
3. in **some cases**, more information is helpful. 

I think **some cases** are: 
-- when an IA currently has a maintainer and that person wants to know they're giving it over to a capable contributor. 

So, to represent it as a nice-to-have (vs. a requirement), I've moved it to the bottom of the process per https://github.com/duckduckgo/duckduckhack-docs/commit/2ba9efe7798797eb3cb255d78842973e05d54df1

**Comment by zachthompson** [comment]
Larger IAs with no maintainer will get maintained by us if necessary.  I don't think we need to know why.  They either will or won't fulfill the responsibilities of the role when it's time.

**Comment by GuiltyDolphin** [comment]
@zachthompson Do we 'revoke' maintainership upon failing to observe the maintainer guidelines? Are there scenarios in which we allow new maintainers other than the 4 week period?

**Comment by zachthompson** [comment]
@GuiltyDolphin Yes, we will need to reset the maintainer fairly often at first, primarily due to timeouts.   We may run into rare cases, e.g. someone just doesn't know what they're doing, is belligerent, doesn't consider enhancements, etc., where we need to decide for other reasons.

**Comment by zachthompson** [comment]
@zekiel I still don't get why it's helpful for us to know why they want to maintain.  Just seeing that language there could give someone pause, if for no other reason than I now feel like I need to supply a reason even though the reason is it's just unmaintained.

Anyhow this is not something we should be changing mid-test because we think it _might_ be useful.

**Comment by GuiltyDolphin** [comment]
@zachthompson Fair enough! Perhaps it is something we may look to in the future (if all goes well) to enhance the quality of maintainers and the suiting of maintainers to Instant Answers?

**Comment by zachthompson** [comment]
@GuiltyDolphin If we find that we need that hurdle from our experience with maintainers, let's address it then.

**Comment by talsraviv** [comment]
Final verdict? Close?

**Comment by zachthompson** [comment]
Yes

**Pull request closed without merging**
