### PR TITLE
Fixed broken link

### PR DESCRIPTION
**Pull request by tagawa**

### CODE REVIEW

**Comment by sahildua2305** [comment]
@tagawa I think this is an important change. Can you please update this PR so that it's merged :smile:

**Comment by nilnilnil** [comment]
:+1:

**Comment by nilnilnil** [comment]
Branch has conflicts and needs resolution. If you make a new PR, with the same content, I will merge it.

**Comment by sahildua2305** [comment]
@nilnilnil Should I make the new PR with same changes? :confused:

**Comment by nilnilnil** [comment]
It has conflicts that render it unmergable until they are resolved. It's Sunday, and @tagawa is probably relaxing. I am saying if you'd like the change merged now, I can do it, but this branch is not mergabel.

**Comment by sahildua2305** [comment]
I just checked, this change was later made [here](https://github.com/duckduckgo/duckduckhack-docs/commit/5699b35d211d363d293b3817f3c50728646a4273) and it's merged as well.

So, all good :smiley:

**Comment by nilnilnil** [comment]
Nice find. Sounds good!

**Comment by tagawa** [comment]
@sahildua2305 @nilnilnil Thanks both of you. I don't usually merge my own pull requests but I probably should have done this time.

**Pull request closed without merging**
