### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Fixes some links that pointed to incorrect IA locations (see more in #19).

### CODE REVIEW

**Comment by moollaza** [comment]
@GuiltyDolphin we recently had ReadmeCritic run on our DuckPAN repo (not sure if it was automatic or requested by someone) but it did a great job of finding _and fixing_ issues in the DuckPAN doc. Would you like to request it to run on here too? I was gonna try and run it locally but didn't find the time yet.

Link: https://github.com/ReadmeCritic/Run

**Comment by GuiltyDolphin** [comment]
@moollaza Huh... Cool, yeah, I'll check it out.

**Comment by GuiltyDolphin** [comment]
@moollaza Well [it ran](https://gist.github.com/ReadmeCritic/3ce1663a2018a932f795). I guess it did as advertised - checked the README.

Didn't check anything else though.

Hopefully the script I wrote (although very slow) has identified all the bad links.

I'll check out `frankenstein` further though.

**Comment by moollaza** [comment]
>  checked the README. Didn't check anything else though.

Crap, thought it would go a little further...

> I'll check out frankenstein further though.

Sweet! Maybe we can alter it to run through all the docs? I'm surprised it doesn't have a facility to look through other files

**Comment by GuiltyDolphin** [comment]
@moollaza I couldn't get frankenstein to work, but `awesome_bot` (the package it uses for checking files) does.

I wrote [a short script](https://gist.github.com/GuiltyDolphin/98cf7ec6aba8a9cc67a9) that uses `awesome_bot` to run through all the files, ~~takes a while though~~ (my bad, script was picking up some bad links, fixed now).

**Comment by talsraviv** [comment]
@GuiltyDolphin this is great. For the record what do you enter into the command line to run the script/any options? Run it in the root of the repo I assume one time?

**Comment by GuiltyDolphin** [comment]
@talsraviv Yeah, I've just moved it into a 'function' so that you can just run `check-docs-links`.

It assumes you have `awesome_bot` installed (via `gem2.0 install awesome_bot --user`).

**Pull request merged**
