### PR TITLE
Cheat Sheet Updates

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Various updates to the cheat sheets docs after the merge of duckduckgo/zeroclickinfo-goodies#2170.

/cc @talsraviv

### CODE REVIEW

**Comment by GuiltyDolphin** [comment]
Zeh merge conflicts!

@talsraviv I think I'm all done unless there's anything you want me to change/add?

**Comment by talsraviv** [comment]
This is looking good - thanks for doing this! Before merging I'd want to get another pair of eyes from @moollaza too but otherwise this is a pretty cool change.

@GuiltyDolphin it would be good to really spell out a few of the template types to contrast so the logic is clearer - it took me a second (and some background reading) to understand that part. 
- Can you list out a few sample triggers of another template type or two? Also can you point out if there are any triggers that all the templates share? 
- Under the templates section, for each template above the screenshot, perhaps list 3-4 sample triggers that are unique to each template (and again pointing out if they share any in common). This is a good section to reinforce this new layer of sophistication.

Otherwise I can take care of the merge conflicts when the time comes to merge I doubt they're insurmountable.

**Comment by talsraviv** [comment]
Or @zachthompson for that matter :)

**Comment by GuiltyDolphin** [comment]
@talsraviv I've dealt with the merge conflicts :wink:

Yeah! I was thinking about adding something (more) to the `Cheat Sheet Templates` section - I'll get on it!

I don't think I'll list _all_ triggers - but hint at what sort of triggers (i.e, a sample of triggers) would be present for each template. If they want to know more they can always peer at the `triggers.yaml` file (which I'll link to).

**Comment by talsraviv** [comment]
LGTM :+1:

**Pull request merged**
