### PR TITLE
changed JSONLint.com to jsoneditoronline.org

### PR DESCRIPTION
**Pull request by gautamkrishnar**
http://jsoneditoronline.org/ will make editing and validating JSON a lot more easier for new contributors.

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@moollaza what did you say?

**Comment by moollaza** [comment]
I prefer JSONLint. If someone is struggling with JSON, it's likely they're very novice and I don't think the JSON Editor GUI, with terms like boolean, array, etc will really help.

Do you have experience with novice developers using this?

**Comment by moollaza** [comment]
@talsraviv any thoughts?

**Comment by gautamkrishnar** [comment]
@moollaza ok :+1: its just a suggestion.

**Comment by gautamkrishnar** [comment]
@duckduckgo/community-leaders what's your opinion on this?

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar I agree with @moollaza about the terminology - looking at that page it would probably just confuse people with limited to no experience of Computer Science.

Doesn't Codio have something for this?

**Comment by gautamkrishnar** [comment]
:+1:

**Comment by gautamkrishnar** [comment]
ok i agree with you guys closing this right now :+1:

**Pull request closed without merging**
