### PR TITLE
Correct some spelling

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
And other minor edits (making naming more consistent).

### CODE REVIEW

**Comment by moollaza** [comment]
@GuiltyDolphin Thanks! This LGTM :+1:

@talsraviv please merge if you're happy!

**Comment by GuiltyDolphin** [comment]
@talsraviv If we can get this merged before any merge conflicts that'd be great - it does modify quite a few files!

**Comment by moollaza** [comment]
We can always revert or modify if needed. Overall this LGTM :+1:

**Comment by talsraviv** [comment]
@GuiltyDolphin awesome! Thank you. Did you do this manually or have a recommended IDE/plugin?

**Comment by GuiltyDolphin** [comment]
@talsraviv I have Vim and Perl ;)

Kindah manual, I had to make sure contexts were appropriate to be changing the spelling. But for detecting the spelling I was mostly using Vim's built-in spell checker.

**Comment by talsraviv** [comment]
Makes sense :)

**Pull request merged**
